### ISSUE TITLE
Can't find Enhancement Implementation Object Type ENHO

### ISSUE THREAD

**Issue by scali96** [Kaszub09/ZABAP_SAP_ENHANCEMENTS#1]
Hi,

the report doesn't show Enhancement Implementation from Object Type ENHO (TADIR).
![image](https://github.com/Kaszub09/ZABAP_SAP_ENHANCEMENTS/assets/162585739/e4ac7b7b-010e-427f-90b9-687c4c5c92c7)

Will this be added in the future?

BR
Marco

**Comment by Kaszub09** [comment]
I will try to add it.
The way it works now is it looks for available enhancement points (be it BADI, user-exit or Enhancement spot) for a program, and only then for their implementation if exists.
So there are two cases:
1. ENHO object is Enhancement spot implementation for one of explicitly declared enhancement spots - in which case it will be visible in report as implementation for this spot.
2. ENHO object is Enhacement spot implementation for implicit enhancement, which isn't declared in TADIR (e.g. it adds a code at the end of FORM in SAP program). In which case this implicit enhancement spot is not visible, so implementation is also not visible.
3. 
It should be possible using ENHOBJ to check which object/packages they are modyfing and add them in the end.

**Comment by Kaszub09** [comment]
Okay, I created another branch and modified report so that implementations of implicit enhancements should also be visible. Please check if it's now visible.

**Comment by scali96** [comment]
Hi,
yes now it is visible.
Thank you!
